#' The PILER DB object
#' 
#' This is the PILER DB object, generated by \code{\link{gen.piler.db}}. The package
#'   ships with its own version of the DB, but it's also possible to build a custom
#'   version.
#'   
#' @format A named list, with the following values:
#' \describe{
#'  \item{summary}{The main "summary" dataframe, which contains a row for each survey, 
#'     along with the relevant indicies. This is the data most analyses will want to use.}
#'  \item{summary.by.group}{Like the summary dataframe, but instead of selecting a group based
#'    on the highest correlation (tau), summary data for each group type are calculated.}
#'  \item{crosstabs}{A list of crosstab data for each survey that is used to generate the
#'    summary. Also contains some summary data about the specific survey.}
#'  \item{group.sizes}{Another dataframe that summarises the entire DB, useful for diagnostics.}
#'  \item{group.sizes.by.group}{The group.sizes data, but by specific groups rather than the
#'    group with the highest tau.}
#'  \item{cat.sum}{Summary information about the categories used for each survey}
#'  \item{data.src.info}{Information about the datasets used to compile the DB}
#'  \item{max.parties}{The maximum number of parties any survey has}
#'  \item{version}{The version of the DB}
#' }
"piler"