#' The PILER DB object
#' 
#' This is the PILER DB object, generated by \code{\link{gen.piler.db}}. The package
#'   ships with its own version of the DB, but it's also possible to build a custom
#'   version.
#'   
#' @format A named list, with the following values:
#' \describe{
#'  \item{survey.summary}{The main "summary" dataframe, which contains a row for each country-survey/group
#'    combination, along with the relevant indicies. Specific versions of these summaries can
#'    be obtained by calling get.survey.summary(). Most analyses will rely on one of these
#'    summaries}
#'  \item{crosstabs}{A list of crosstab data for each survey that is used to generate the
#'    summary. Also contains some summary data about the specific survey.}
#'  \item{group.sizes}{Another dataframe that summarises the entire DB, useful for diagnostics.}
#'  \item{group.sizes.by.group}{The group.sizes data, but by specific groups rather than the
#'    group with the highest PES.}
#'  \item{country.summaries}{Contains some country-level summary data}
#'  \item{cat.sum}{Summary information about the categories used for each survey}
#'  \item{data.src.info}{Information about the datasets used to compile the DB}
#'  \item{max.parties}{The maximum number of parties any survey has}
#'  \item{version}{The version of the DB}
#' }
"piler"